import socket
import threading
import tkinter as tk

# This program acts as the server in the Smart Traffic Monitoring System.
# It receives traffic data sent via UDP from the client (which reads the simulation data).
# The data was originally generated by a SUMO simulation and stored in a JSON file.
# The client replays this data and sends it packet-by-packet to this server.
# This server continuously listens for incoming data, processes it,
# and updates a Tkinter UI to display traffic conditions in real-time.

SERVER_IP = "127.0.0.1"
SERVER_PORT = 9999

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((SERVER_IP, SERVER_PORT))

root = tk.Tk()
root.title("Smart Traffic Monitoring System")
root.geometry("450x320")

title = tk.Label(root, text="Traffic Monitoring Dashboard", font=("Arial",16))
title.pack(pady=10)

vehicle_label = tk.Label(root, text="Vehicles: 0", font=("Arial",12))
vehicle_label.pack()

queue_label = tk.Label(root, text="Queue Length: 0", font=("Arial",12))
queue_label.pack()

wait_label = tk.Label(root, text="Waiting Time: 0", font=("Arial",12))
wait_label.pack()

signal_label = tk.Label(root, text="Signal: -", font=("Arial",12))
signal_label.pack()

status_label = tk.Label(root, text="Status: NORMAL", font=("Arial",14))
status_label.pack(pady=10)

# Determines traffic condition based on queue length and waiting time

def analyze(queue, wait):
    if queue < 5 and wait < 10:
        return "NORMAL"
    elif queue < 15:
        return "MODERATE"
    else:
        return "SEVERE"
        # Determines traffic condition based on queue length and waiting time

def listen():
    while True:
        data, addr = sock.recvfrom(65535)

        # 🔹 Decode CSV message
        message = data.decode()
        parts = message.split(",")

        # 🔹 Parse values
        timestamp = parts[0]
        simulation_time = float(parts[1])
        vehicle_count = int(parts[2])
        north = int(parts[3])
        south = int(parts[4])
        east = int(parts[5])
        west = int(parts[6])
        waiting_time = float(parts[7])
        signal_state = parts[8]

        total_queue = north + south + east + west
        status = analyze(total_queue, waiting_time)

        # 🔹 Update UI
        vehicle_label.config(text=f"Vehicles: {vehicle_count}")
        queue_label.config(text=f"Queue Length: {total_queue}")
        wait_label.config(text=f"Waiting Time: {waiting_time}")
        signal_label.config(text=f"Signal: {signal_state}")

        if status == "NORMAL":
            status_label.config(text="🟢 NORMAL", fg="green")
        elif status == "MODERATE":
            status_label.config(text="🟡 MODERATE", fg="orange")
        else:
            status_label.config(text="🔴 SEVERE", fg="red")

        print("Received:", message)

thread = threading.Thread(target=listen, daemon=True)
thread.start()

root.mainloop()
