import socket
import threading
import tkinter as tk
from tkinter import scrolledtext
from datetime import datetime

# This program acts as the server in the Smart Traffic Monitoring System.
# It receives traffic data sent via UDP from the client (which reads simulation data).
# The data was originally generated by a SUMO simulation and stored in a JSON file.
# The client replays this data and sends it packet-by-packet to this server.
# This server continuously listens for incoming data, processes it,
# and updates a Tkinter UI to display traffic conditions in real-time.

expected_seq = 0
packets_lost = 0

SERVER_IP = "127.0.0.1"
SERVER_PORT = 9999

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((SERVER_IP, SERVER_PORT))

root = tk.Tk()
root.title("Smart Traffic Monitoring System")
root.geometry("500x520")
root.configure(bg="#1a1a2e")

# ── Title ──────────────────────────────────────────────────────────────
title = tk.Label(
    root, text="Traffic Monitoring Dashboard",
    font=("Arial", 16, "bold"), bg="#1a1a2e", fg="#e0e0e0"
)
title.pack(pady=10)

# ── Stats Frame ────────────────────────────────────────────────────────
stats_frame = tk.Frame(root, bg="#16213e", pady=8, padx=10)
stats_frame.pack(fill="x", padx=15)

vehicle_label = tk.Label(stats_frame, text="Vehicles: 0",      font=("Arial", 12), bg="#16213e", fg="#a0c4ff")
vehicle_label.grid(row=0, column=0, sticky="w", padx=10)

queue_label   = tk.Label(stats_frame, text="Queue Length: 0",  font=("Arial", 12), bg="#16213e", fg="#a0c4ff")
queue_label.grid(row=0, column=1, sticky="w", padx=10)

wait_label    = tk.Label(stats_frame, text="Waiting Time: 0",  font=("Arial", 12), bg="#16213e", fg="#a0c4ff")
wait_label.grid(row=1, column=0, sticky="w", padx=10, pady=4)

signal_label  = tk.Label(stats_frame, text="Signal: -",        font=("Arial", 12), bg="#16213e", fg="#a0c4ff")
signal_label.grid(row=1, column=1, sticky="w", padx=10)

loss_label = tk.Label(
    stats_frame, text="Packets Lost: 0",
    font=("Arial", 12), bg="#16213e", fg="#ff8080"
)
loss_label.grid(row=2, column=0, sticky="w", padx=10, pady=4)
loss_label.config(text=f"Packets Lost: {packets_lost}")

# ── Status Badge ───────────────────────────────────────────────────────
status_label = tk.Label(
    root, text="Status: NORMAL",
    font=("Arial", 14, "bold"), bg="#1a1a2e", fg="green"
)
status_label.pack(pady=8)

# ── Alert Log ──────────────────────────────────────────────────────────
log_frame = tk.Frame(root, bg="#1a1a2e")
log_frame.pack(fill="both", expand=True, padx=15, pady=(0, 5))

log_header = tk.Label(
    log_frame, text="🔔  Alert Log",
    font=("Arial", 11, "bold"), bg="#1a1a2e", fg="#f0a500", anchor="w"
)
log_header.pack(fill="x")

alert_log = scrolledtext.ScrolledText(
    log_frame, height=10, state="disabled",
    font=("Courier", 9), bg="#0f0f1a", fg="#d0d0d0",
    insertbackground="white", relief="flat", bd=0
)
alert_log.pack(fill="both", expand=True)

# Colour tags for severity levels
alert_log.tag_config("SEVERE",   foreground="#ff4c4c")
alert_log.tag_config("MODERATE", foreground="#ffb347")
alert_log.tag_config("NORMAL",   foreground="#77dd77")
alert_log.tag_config("TIME",     foreground="#888888")

# Track last status so we only log on change
last_status = {"value": None}

# ── Helpers ────────────────────────────────────────────────────────────

def analyze(queue, wait):
    """Determine traffic condition based on queue length and waiting time."""
    if queue < 5 and wait < 10:
        return "NORMAL"
    elif queue < 15:
        return "MODERATE"
    else:
        return "SEVERE"


def log_alert(status, queue, wait):
    """Append a timestamped entry to the alert log (status-change only)."""
    ts = datetime.now().strftime("%H:%M:%S")
    entry = f"[{ts}]  {status:<8}  queue={queue}  wait={wait:.1f}s\n"

    alert_log.config(state="normal")
    alert_log.insert("end", f"[{ts}]  ", "TIME")
    alert_log.insert("end", f"{status:<8}", status)
    alert_log.insert("end", f"  queue={queue}  wait={wait:.1f}s\n")
    alert_log.see("end")          # auto-scroll to latest
    alert_log.config(state="disabled")


# ── UDP Listener ───────────────────────────────────────────────────────

def listen():
    while True:
        data, addr = sock.recvfrom(65535)

        # Decode CSV message
        message = data.decode()
        parts   = message.split(",")

        seq_num = int(parts[0])
        # Parse values
        timestamp       = parts[1]
        simulation_time = float(parts[2])
        vehicle_count   = int(parts[3])
        north           = int(parts[4])
        south           = int(parts[5])
        east            = int(parts[6])
        west            = int(parts[7])
        waiting_time    = float(parts[8])
        signal_state    = parts[9]

        global expected_seq, packets_lost

        if seq_num != expected_seq:
            lost = seq_num - expected_seq
            if lost > 0:
                packets_lost += lost
                print(f"⚠️ Packet loss detected: {lost} packets")

        expected_seq = seq_num + 1

        total_queue = north + south + east + west
        status      = analyze(total_queue, waiting_time)

        # Update live stats
        vehicle_label.config(text=f"Vehicles: {vehicle_count}")
        queue_label.config(  text=f"Queue Length: {total_queue}")
        wait_label.config(   text=f"Waiting Time: {waiting_time:.1f}s")
        signal_label.config( text=f"Signal: {signal_state}")

        if status == "NORMAL":
            status_label.config(text="🟢 NORMAL",   fg="#77dd77")
        elif status == "MODERATE":
            status_label.config(text="🟡 MODERATE", fg="#ffb347")
        else:
            status_label.config(text="🔴 SEVERE",   fg="#ff4c4c")

        # Log alert only when status changes
        if status != last_status["value"]:
            log_alert(status, total_queue, waiting_time)
            last_status["value"] = status

        print("Received:", message)


thread = threading.Thread(target=listen, daemon=True)
thread.start()

root.mainloop()
