import socket
import threading
import tkinter as tk

# This program acts as the server in the Smart Traffic Monitoring System.
# It receives traffic data sent via UDP from the client (which reads the simulation data).
# The data was originally generated by a SUMO simulation and stored in a JSON file.
# The client replays this data and sends it packet-by-packet to this server.
# This server continuously listens for incoming data, processes it,
# and updates a Tkinter UI to display traffic conditions in real-time.

SERVER_IP = "127.0.0.1"
SERVER_PORT = 9999

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((SERVER_IP, SERVER_PORT))

print("Server UP AND RUNNING...")

#To Track lost packets and calculate loss rate
expected_packet = 0
lost_packets = 0
total_received = 0

#UI Tkinter Setup
root = tk.Tk()
root.title("Smart Traffic Monitoring System")
root.geometry("450x380")

title = tk.Label(root, text="Traffic Monitoring Dashboard", font=("Arial",16))
title.pack(pady=10)

vehicle_label = tk.Label(root, text="Vehicles: 0", font=("Arial",12))
vehicle_label.pack()

queue_label = tk.Label(root, text="Queue Length: 0", font=("Arial",12))
queue_label.pack()

wait_label = tk.Label(root, text="Waiting Time: 0", font=("Arial",12))
wait_label.pack()

signal_label = tk.Label(root, text="Signal: -", font=("Arial",12))
signal_label.pack()

status_label = tk.Label(root, text="Status: NORMAL", font=("Arial",14))
status_label.pack(pady=10)

loss_label = tk.Label(root, text="Packets Lost: 0", font=("Arial",12))
loss_label.pack()

loss_rate_label = tk.Label(root, text="Loss %: 0.0", font=("Arial",12))
loss_rate_label.pack()

# Determines traffic condition based on queue length and waiting time

def analyze(queue, wait):
    if queue < 5 and wait < 10:
        return "NORMAL"
    elif queue < 15:
        return "MODERATE"
    else:
        return "SEVERE"

def update_ui(vehicle_count, total_queue, waiting_time, signal_state, status, loss_rate):
    vehicle_label.config(text=f"Vehicles: {vehicle_count}")
    queue_label.config(text=f"Queue Length: {total_queue}")
    wait_label.config(text=f"Waiting Time: {waiting_time:.2f}")
    signal_label.config(text=f"Signal: {signal_state}")
    loss_label.config(text=f"Packets Lost: {lost_packets}")
    loss_rate_label.config(text=f"Loss %: {loss_rate:.2f}")

    if status == "NORMAL":
        status_label.config(text="🟢 NORMAL", fg="green")
    elif status == "MODERATE":
        status_label.config(text="🟡 MODERATE", fg="orange")
    else:
        status_label.config(text="🔴 SEVERE", fg="red")

def listen():
    global expected_packet, lost_packets, total_received

    while True:
        try:
            data, addr = sock.recvfrom(65535)

            #Decoding the received data and splitting it into parts
            message = data.decode()
            print("Received:", message)

            parts = message.split(",")

            # Packet ID
            packet_id = int(parts[0])

            # Packet loss detection
            if packet_id != expected_packet:
                lost = packet_id - expected_packet
                if lost > 0:
                    lost_packets += lost
                    print(f"⚠️ Lost {lost} packets")

            expected_packet = packet_id + 1
            total_received += 1

            # Parse data
            timestamp = parts[1]
            simulation_time = float(parts[2])
            vehicle_count = int(parts[3])
            north = int(parts[4])
            south = int(parts[5])
            east = int(parts[6])
            west = int(parts[7])
            waiting_time = float(parts[8])
            signal_state = parts[9]

            total_queue = north + south + east + west
            status = analyze(total_queue, waiting_time)

            total_packets = total_received + lost_packets
            loss_rate = (lost_packets / total_packets) * 100 if total_packets > 0 else 0

            # Safe UI update
            root.after(0, update_ui, vehicle_count, total_queue, waiting_time, signal_state, status, loss_rate)

        except Exception as e:
            print("❌ ERROR:", e)

# Start listening thread
thread = threading.Thread(target=listen, daemon=True)
thread.start()

root.mainloop()